In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
from operator import itemgetter

In [ ]:
G = nx.read_graphml('/london.graph')

In [ ]:
#  We can calculate the degree centrality using networkx function:
deg_london =nx.degree_centrality(G)
nx.set_node_attributes(G,dict(deg_london),'degree')
#print(deg_london)

In [ ]:
# To dataframe using the nodes as the index
#nx.set_edge_attributes(G,nod_name1,'source')
#nx.set_edge_attributes(G,nod_name2,'station_2_')

df = pd.DataFrame(index=G.nodes())
nx.get_node_attributes(G, 'degree')
df['degree'] = pd.Series(nx.get_node_attributes(G, 'degree'))

df_sorted = df.sort_values(["degree"], ascending=False)
df_sorted[0:10]

                          degree
Stratford                 0.0225
Bank and Monument         0.0200
King's Cross St. Pancras  0.0175
Baker Street              0.0175
Earl's Court              0.0150
Oxford Circus             0.0150
Liverpool Street          0.0150
Waterloo                  0.0150
Green Park                0.0150
Canning Town              0.0150

In [ ]:
### Weighted betweenness centrality:
#Let us compute the betweenness centrality for the network, considering the distance between stations:

bet_london_w=nx.betweenness_centrality(G,weight='length',normalized=False)
#bet_london_w=nx.betweenness_centrality(G)
# We can add these values to the nodes attributes:
nx.set_node_attributes(G,bet_london_w,'betweenness_w')

In [ ]:
# To dataframe using the nodes as the index
df = pd.DataFrame(index=G.nodes())
#df['station_name'] = pd.Series(nx.get_node_attributes(G, 'station_name'))
df['betweenness_w'] = pd.Series(nx.get_node_attributes(G, 'betweenness_w'))

df_sorted = df.sort_values(["betweenness_w"], ascending=False)
df_sorted[0:10]

                          betweenness_w
Bank and Monument               17656.0
King's Cross St. Pancras        16693.0
Stratford                       14548.0
Oxford Circus                   13561.0
Euston                          13240.0
Baker Street                    12150.0
Earl's Court                    11475.0
Shadwell                        11128.0
Waterloo                        10408.0
South Kensington                10335.0

In [ ]:
### Topological betweenness centrality:

#Let us compute the betweenness centrality for the network, without using weights:
bet_london_t=nx.betweenness_centrality(G, normalized=False)
# We can add these values to the nodes attributes:
nx.set_node_attributes(G,bet_london_t,'betweenness_t')

# To ataframe using the nodes as the index
df = pd.DataFrame(index=G.nodes())
#df['station_name'] = pd.Series(nx.get_node_attributes(G, 'station_name'))
df['betweenness_t'] = pd.Series(nx.get_node_attributes(G, 'betweenness_t'))

df_sorted = df.sort_values(["betweenness_t"], ascending=False)
df_sorted[0:10]

                          betweenness_t
Stratford                  23768.093434
Bank and Monument          23181.058947
Liverpool Street           21610.387049
King's Cross St. Pancras   20373.521465
Waterloo                   19464.882323
Green Park                 17223.622114
Euston                     16624.275469
Westminster                16226.155916
Baker Street               15287.107612
Finchley Road              13173.758009

In [ ]:
#Let us compute the betweenness centrality for the network, but this time lets do it in the edges!
bet_london_e=nx.edge_betweenness_centrality(G, normalized=False, weight='length')
# We can add these values to the edges attributes:
nx.set_edge_attributes(G,bet_london_e,'betweenness_e')

#### Closeness Centrality:

In [ ]:
#Weighted closeness centrality: 
clos_w=nx.closeness_centrality(G, distance='length')
# We can add these values to the nodes attributes:
nx.set_node_attributes(G,clos_w,'closeness_w')

# To ataframe using the nodes as the index
df = pd.DataFrame(index=G.nodes())
#df['station_name'] = pd.Series(nx.get_node_attributes(G, 'station_name'))
df['closeness_w'] = pd.Series(nx.get_node_attributes(G, 'closeness_w'))

df_sorted = df.sort_values(["closeness_w"], ascending=False)
df_sorted[0:10]

                          closeness_w
Holborn                      0.000079
King's Cross St. Pancras     0.000079
Tottenham Court Road         0.000079
Oxford Circus                0.000079
Leicester Square             0.000078
Piccadilly Circus            0.000078
Charing Cross                0.000078
Chancery Lane                0.000078
Covent Garden                0.000078
Embankment                   0.000078

In [ ]:
#topological closeness centrality
clos_t=nx.closeness_centrality(G)
# We can add these values to the nodes attributes:
nx.set_node_attributes(G,clos_t,'closeness_t')

# To ataframe using the nodes as the index
df = pd.DataFrame(index=G.nodes())
#df['station_name'] = pd.Series(nx.get_node_attributes(G, 'station_name'))
df['closeness_t'] = pd.Series(nx.get_node_attributes(G, 'closeness_t'))

df_sorted = df.sort_values(["closeness_t"], ascending=False)
df_sorted[0:10]

                          closeness_t
Green Park                   0.114778
Bank and Monument            0.113572
King's Cross St. Pancras     0.113443
Westminster                  0.112549
Waterloo                     0.112265
Oxford Circus                0.111204
Bond Street                  0.110988
Farringdon                   0.110742
Angel                        0.110742
Moorgate                     0.110314

In [ ]:
G2=G

In [ ]:
#########code for 1.3 and 2.3 non-sequential removal#########
# To remove  10 highest values:
# List of nodes
def get_remove_nodes(centrality):
    values_sorted = sorted(centrality.items(), key=itemgetter(1), reverse=True)
    sorted_ten=[e for e,v in values_sorted[:10]]
    return sorted_ten

In [ ]:
#Remove nodes:
#print(list(G2.nodes))


def get_max_component(G2):
    # To obtain the largest component as a new graph: 

    # Get the list of components:
    components = nx.connected_components(G2)
    # Use the max() command to find the largest one:
    largest_component = max(components, key=len)
    # Create a "subgraph" of the largest component
    Largest_subgraph = G2.subgraph(largest_component)
    return Largest_subgraph
G = nx.read_graphml('/london.graph')
G2=G
#sorted_ten=get_remove_nodes(deg_london)
#sorted_ten=get_remove_nodes(clos_t)
sorted_ten=get_remove_nodes(bet_london_t)
sorted_ten
for i in range(len(sorted_ten)):
    G2.remove_nodes_from([sorted_ten[i]])
    print(nx.info(G2))
    
    is_connected=nx.is_connected(G2)
   
    Largest_subgraph=get_max_component(G2)
    number_of_nodes=Largest_subgraph.number_of_nodes()
    diameter = nx.diameter(Largest_subgraph)
    components=nx.number_connected_components(G2)
  #  print("After remove the ",sorted_ten[i],"node, for the largest subgraph","the number_of_nodesis",number_of_nodes, "diameter is",diameter,"components is",components)

Graph with 400 nodes and 458 edges
Graph with 399 nodes and 450 edges
Graph with 398 nodes and 446 edges
Graph with 397 nodes and 439 edges
Graph with 396 nodes and 434 edges
Graph with 395 nodes and 428 edges
Graph with 394 nodes and 424 edges
Graph with 393 nodes and 422 edges
Graph with 392 nodes and 415 edges
Graph with 391 nodes and 412 edges

In [ ]:
#########code for 1.3 and 2.3 sequential removal#########

def get_remove_nodes(centrality):
    values_sorted = sorted(centrality.items(), key=itemgetter(1), reverse=True)
    sorted_one=[e for e,v in values_sorted[:1]]
    return sorted_one

def get_max_component(G2):
    # To obtain the largest component as a new graph: 

    # Get the list of components:
    components = nx.connected_components(G2)
    # Use the max() command to find the largest one:
    largest_component = max(components, key=len)
    # Create a "subgraph" of the largest component
    Largest_subgraph = G2.subgraph(largest_component)
    return Largest_subgraph
G = nx.read_graphml('/london.graph')

G2=G

for i in range(10):
    centrality=nx.betweenness_centrality(G2, normalized=False)
    #centrality=nx.closeness_centrality(G2)#求不带权重的closeness
   # centrality =nx.degree_centrality(G2)#求度数
    sorted_one=get_remove_nodes(centrality)
    G2.remove_nodes_from(sorted_one)
    print(nx.info(G2))
    
    is_connected=nx.is_connected(G2)
   
    Largest_subgraph=get_max_component(G2)
    number_of_nodes=Largest_subgraph.number_of_nodes()
    diameter = nx.diameter(Largest_subgraph)
    components=nx.number_connected_components(G2)
  #  print("After remove the ",sorted_one,"node, for the largest subgraph","the number_of_nodesis",number_of_nodes, "diameter is",diameter,"components is",components)

Graph with 400 nodes and 458 edges
Graph with 399 nodes and 451 edges
Graph with 398 nodes and 445 edges
Graph with 397 nodes and 438 edges
Graph with 396 nodes and 434 edges
Graph with 395 nodes and 430 edges
Graph with 394 nodes and 424 edges
Graph with 393 nodes and 420 edges
Graph with 392 nodes and 416 edges
Graph with 391 nodes and 409 edges